name: tablexplore
version: 'latest'
#version-script: git describe --abbrev=1 --tags
summary: data plotting and analysis package
description: |
  tablexplore is an open source desktop application for data analysis and plotting
  intended for use in both research and education. The program allows quick
  visualization of data, table manipulation tools and supports large data tables.

base: core18
grade: stable
confinement: strict
icon: gui/icon.png

apps:
  tablexplore:
    command: desktop-launch $SNAP/bin/tablexplore
    environment:
      #PYTHONPATH: $SNAP/pyside/pyside
      #LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$ARCH/dri
      XCOMPOSEFILE: $SNAP/usr/share/X11/locale/en_US.UTF-8/Compose
      FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
    plugs:
      - opengl
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - home

parts:
  tablexplore:
    plugin: python
    source: .
    stage-packages:  
      - libnss3
      - libxcomposite1
      - libxcursor1
      - libxtst6
      - libxrandr2
      - libasound2
      - libglu1-mesa
      - libgles2-mesa
      - fontconfig
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxi6
      - libegl1
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - libxslt1.1
      - xfonts-base
      - xfonts-scalable

#layout:
#  /usr/share/fonts:
#    bind: $SNAP/pyside/usr/share/fonts
#  /etc/fonts:
#    bind: $SNAP/pyside/etc/fonts
